# Generated by Django 3.1.4 on 2020-12-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizdb',
            name='name',
        ),
        migrations.AddField(
            model_name='quizdb',
            name='answer',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='quizdb',
            name='option1',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='quizdb',
            name='option2',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='quizdb',
            name='option3',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='quizdb',
            name='option4',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='quizdb',
            name='question',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='quizdb',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='quizdb',
            table='quest',
        ),
    ]
